### ISSUE TITLE
Running `http://localhost:8000/api/races/{race_id}/start` is throwing an error

### ISSUE THREAD

**Issue by anku580** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#6]
Hi, 

The `server.exe` is throwing the following error in the terminal when I try to start the race using `http://localhost:8000/api/races/1/start` endpoint. Before invoking this endpoint, I ran the `http://localhost:8000/api/races` endpoint to create the race. It successfully gave me the race id. 

### Created the race successfully
![image](https://user-images.githubusercontent.com/25228101/82140669-12e3a000-984e-11ea-9c61-61350163bc3d.png)

### Starting the race is giving an error
![image](https://user-images.githubusercontent.com/25228101/82140678-22fb7f80-984e-11ea-9675-788dce7f8872.png)

### Server terminal throwing an error while starting the race
![image](https://user-images.githubusercontent.com/25228101/82140684-30186e80-984e-11ea-9c7c-ff20c8e105ad.png)

**Comment by saleh-tavassoli** [comment]
@anku580 Do you have a new update on this? I assume submitting project while this endpoint doesn't respond, won't be possible.

**Comment by anku580** [comment]
Hi @saleh-tavassoli still no updates on it. I've submitted the project by completing the rest of the functions.

**Comment by fanyui** [comment]
Hi @saleh-tavassoli  That endpoint has a little issue but you can fix it by subtracting one from the race_id before sending it
ie `race_Id-1`

**Comment by sreejithvs333** [comment]
race_Id-1 not working for me :(

**Comment by fanyui** [comment]
Hi @sreejithvs333 
What you have done should normally work. However since according to you it seems not to work,
I assume you are taking the intermediate javascript nano degree if you find this repository. Can you ask a question in knowledge regarding your issue?, 
A mentor will assist you in debugging, Happy learning :)

**Comment by tlebon** [comment]
is this error seriously 8 months old and you guys haven't changed it? Wild stuff.

**Comment by sandeep2194** [comment]
when you call the API use ID minus 1 as your ID and everything starts working

**Comment by chrissygonzalez** [comment]
Annoying! I spent an hour on this before checking the issues. Going to read through the rest of the issues now and hopefully save myself some time.

**Comment by jepster** [comment]
Hi!

It's really annoying that the intermediate JavaScript course is so buggy since more than 8 months. It's especially annoying for JavaScript beginners, which are bumping their heads against a buggy API, which is provided by a compiled binary!

I have tried to subtract 1 from the **raceId** which I got from the **binary server**. I am working on MacOS. However, I am getting the same result.

You can check my project on Github via the following url: https://github.com/jepster/UdaciRacerSimulationGame

1. I am starting the binary server on MacOS via: **ORIGIN_ALLOWED=http://localhost:3000 bin/server-osx**
2. Then I am starting the frontend server: **npm start**
3. I do compile my changes via a watching webpack command: **npm run build-dev**
4. Afterwards I can visit my project via the webbrowser by the following url: http://localhost:3000

My current createRace() function with the -1 workaround:
```
async function createRace(player_id, track_id) {
	player_id = parseInt(player_id)
	track_id = parseInt(track_id)
	const body = { player_id, track_id }
	await fetch(`${SERVER}/api/races`, {
		method: "POST",
		...defaultFetchOpts(),
		dataType: "jsonp",
		body: JSON.stringify(body),
	})
		.then((res) => res.json())
		.then((res) => {
			console.log(`Then response from: ${SERVER}/api/races`);
			console.log(res);
			store.race_id = parseInt(res.ID) - 1; //here to store the race_id that we get from the API
			store.player_id = res.PlayerID;
			console.log('Finished race creation.');
		})
		.catch((err) => console.log("Problem with createRace request::", err));
}
```

If the raceId from the server is 2, I am sending 1 as the further requests to the server:
```
client.js:416 POST http://localhost:8000/api/races/1/start net::ERR_EMPTY_RESPONSE
client.js:420 Problem with startRace request:: TypeError: Failed to fetch
```

The startRace() function looks like follows:
```
async function startRace(id) {
	console.log('BEGIN - Starting race!');
	await fetch(`${SERVER}/api/races/${id}/start`, {
		method: 'POST',
		...defaultFetchOpts(),
	})
		.catch(error => console.log("Problem with startRace request::", error))
	console.log('END - Starting race!');
	console.log(`BEGIN - ${SERVER}/api/races/${id}`);
	await fetch(`${SERVER}/api/races/${id}`)
		.then(response => {
			console.log(`Info for request: ${SERVER}/api/races/${id}`);
			console.log(response.json())
		})
		.catch(error => console.log(error))
	console.log(`END - ${SERVER}/api/races/${id}`);
}
```
Could you please point me to any solution or "bug workarounds" here?

**Comment by javiermolsanz** [comment]
I'm having the same problem @jepster, can you confirm if you managed to resolve it?

**Comment by jepster** [comment]
You must subtract -1 from the race ID. There was also a different issue in my code and I resolved it by submitting the project and asking a mentor. The reviewer helped.

**Comment by ahmedmeshref** [comment]
Basically, the backend uses natural numbers to represent the race ID and index for getting a specific race by ID. The solution is to use race.ID - 1 in your calls.

**Comment by osamaxsyed** [comment]
For me I still have the issue after subtracting 1 from the raceID. I only get an error when raceId from the server is 2 and I send 1 for further requests. 

The error only happens for startRace(id) and getRace(id) when id === 1. 

After attempting to try the race again and the raceId from the server is 3 and after subtracting I send 2 to startRace(id) and getRace(id) when id === 2. I have no issues running the race.

For some reason the API cannot handle an id of 1 being sent.

**Comment by UAnjali** [comment]
Hi,
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
